name: Continuous Deployment
run-name: ${{ github.actor }} CD ðŸš€
on:
  release:
    types: [published]
  push:
    branches:
      - '*'
jobs:
  cd:
    uses: ./.github/workflows/cd.yml
    with:
      python-version: 3.9
      poetry-version: 1.4.0
      os: ubuntu-latest
